fabric_generator:file_parser: Refactor parseFileVHDL
FPGA-Research-Manchester/FABulous pull request #177
Opened 2024-05-14 15:17 UTC by EverythingElseWasAlreadyTaken

Refactor parseFileVHDL to make it more readable.
This fixes also the bug, that shared INPUT ports in VHDL files, were added as INOUT ports.

Add port direction variable in parseFileVerilog function to make it more readable.

Some cosmetic changes.

2024-05-14 18:57 UTC, KelvinChung2000 commented
I have done something similar recently. You can check out [here](https://github.com/KelvinChung2000/FABulous/commit/6db4e6fb2cd7fcc0c3af79152b8161aa2ebda001#diff-771374aab3db1156c58027c5be11f12a5bebac2f451f82b912fb1d8987e61b85). If this is helpful for you I will make a pull request publish that out.

2024-05-15 13:34 UTC, EverythingElseWasAlreadyTaken commented
> I have done something similar recently. You can check out [here](https://github.com/KelvinChung2000/FABulous/commit/6db4e6fb2cd7fcc0c3af79152b8161aa2ebda001#diff-771374aab3db1156c58027c5be11f12a5bebac2f451f82b912fb1d8987e61b85). If this is helpful for you I will make a pull request publish that out.

Thanks for the hint, but I see some issues with your changes for the parseFileVerilog/VHDL.
For the parseFIleVHDL, you still have this big chunk of if-else statements, which is already fixed in the parseFileVerilog. Also in the parseFileVerilog, you are treating INOUT ports always as OUTPUT ports, since you only check for INPUT ports. 

The other changes are quite nice, we should somehow combine them. 
Or you could accept this PR and rebase your commit to this. 

I've also though about, combining the parseFileVHDL and parseFileVerilog in one function, since the code is like 80% same. 
This would improve the maintainability and reduce the likelyhood for errors.

2024-05-15 15:17 UTC, KelvinChung2000 commented
The main problem with combining is the subtle difference in parsing. You will have one blob for Verilog and another for VHDL, which might make the code look bulky again. But this should indeed reduce the amount of things that need maintenance. 

I will rebase mine on yours later. But I have other things to do first, so that won't happen soon. 

The ideal way would be to do it in a parser way, which reads in both Verilog and VHDL, and then we extract data under a common AST... But this in itself will be a project.

2024-05-16 08:49 UTC, EverythingElseWasAlreadyTaken commented
> The main problem with combining is the subtle difference in parsing. You will have one blob for Verilog and another for VHDL, which might make the code look bulky again. But this should indeed reduce the amount of things that need maintenance.

Yes, but I think this will mostly concern the regex lines. 

> I will rebase mine on yours later. But I have other things to do first, so that won't happen soon.

Okay. Sure, there is no rush. 

> The ideal way would be to do it in a parser way, which reads in both Verilog and VHDL, and then we extract data under a common AST... But this in itself will be a project.

Yes, this would be really nice, but this will be indeed a big project.

2024-05-16 09:31 UTC, KelvinChung2000 commented
Since you are refactoring, you can include it here as well and rename the PR to mention refactoring both.

2024-05-21 11:48 UTC, EverythingElseWasAlreadyTaken commented
> Since you are refactoring, you can include it here as well and rename the PR to mention refactoring both.

I've merged them into one parseFile function now.
Would be nice if you could review my changes. :)

2024-07-10 10:12 UTC, EverythingElseWasAlreadyTaken commented
@KelvinChung2000 have you already had some time to look at it again?

I have some other works that are partly based on this.

2024-07-10 10:17 UTC, KelvinChung2000 commented
I have put some comments on it. I am not sure why when I made an review it did not notify you

2024-07-10 10:18 UTC, KelvinChung2000 requested changes

2024-07-10 10:18 UTC, KelvinChung2000 commented on FABulous/fabric_generator/file_parser.py
> +                    direction = None
We can raise a value error here since we will never reach this point.  With the raise, it should also notify the static checker that `direction` is always defined.

2024-07-10 10:18 UTC, KelvinChung2000 commented on FABulous/fabric_generator/file_parser.py
>      return internal, external, config, shared, noConfigBits, userClk, belMapDic
This is a historical mess that I made. We can create the `Bel` object here instead of doing it at the main parser logic. This will also allow the function to be used standalone, and much easier to use.

2024-07-10 10:18 UTC, KelvinChung2000 commented
Does it work now?

2024-07-10 10:22 UTC, KelvinChung2000 approved these changes

2024-07-10 11:11 UTC, EverythingElseWasAlreadyTaken commented
> Does it work now?

Yes, saw the Review now, but I didn't get any notifications before this. 

Thanks, I'll look into this :)

2024-07-10 12:44 UTC, EverythingElseWasAlreadyTaken commented on FABulous/fabric_generator/file_parser.py
> +                    direction = None
Fixed :)

2024-07-10 12:44 UTC, EverythingElseWasAlreadyTaken commented on FABulous/fabric_generator/file_parser.py
>      return internal, external, config, shared, noConfigBits, userClk, belMapDic
Fixed :)

2024-07-10 13:16 UTC, merged