Fix backward compatibility to old project structure and some housekeeping
FPGA-Research-Manchester/FABulous pull request #233
Opened 2024-09-18 13:15 UTC by EverythingElseWasAlreadyTaken

Fix backward compatibility to old project structure: 
- Add case for old tcl scripts in run_FABulous_bitstream.
- ConfigMemPath in fabric_gen:generateBitstreamSpec was set wrong, if a project used the old fabric.csv structure.

Remove unneeded get_path() function and use Path() instead of pathlib.Path()

Add check if external programs are installed

2024-09-18 14:21 UTC, IAmMarcelJung requested changes
Thanks for this! :) As always I just found some typos.

2024-09-18 14:21 UTC, IAmMarcelJung commented on FABulous/FABulous.py
> +                    "run_FABulous_bitstream does not support vpr anymore, please use npnr or try a older FABulous version."
```suggestion
                    "run_FABulous_bitstream does not support vpr anymore, please use npnr or try an older FABulous version."
```

2024-09-18 14:21 UTC, IAmMarcelJung commented on FABulous/FABulous.py
> +            raise Exception(f"{application} is not installed.")
```suggestion
def check_if_application_exists(application: str, throw_exception: bool = True) -> Path:
    """Checks if an application is installed on the system.

    Parameters
    ----------
    application : str
        Name of the application to check.
    throw_exception : bool, optional
        If True, throws an exception if the application is not installed, by default True

    Returns
    -------
    Path
        Path to the application, if installed.

    Raises
    ------
    Exception
        If the application is not installed and throw_exception is True.
    """
    path = shutil.which(application)
    if path is not None:
        return Path(path)
    else:
        logger.error(
            f"{application} is not installed. Please install it or set FAB_<APPLICATION>_PATH in the .env file."
        )
        if throw_exception:
            raise Exception(f"{application} is not installed.")
```

2024-09-18 14:21 UTC, IAmMarcelJung commented on FABulous/fabric_generator/file_parser.py
> +            # TODO: if old fabric.csv tileDir is set wrong
Is the TODO supposed to be still in there to be fixed in the future? Or was it just missed?

2024-09-18 14:26 UTC, KelvinChung2000 commented
I think we can stop supporting the 1.0 file structure format. We can do all the breaking changes in 2.0.

2024-09-18 14:39 UTC, EverythingElseWasAlreadyTaken commented
> I think we can stop supporting the 1.0 file structure format. We can do all the breaking changes in 2.0.

Generally I'm okay with this, but then we should find a proper handling for this, like throwing proper Errors for this.
Since currently, with old projects, the ConfigMem generation just stopped working, but the flow just broke at Place and Route step. 
 And this fix was a relatively easy to implement,

2024-09-25 10:15 UTC, EverythingElseWasAlreadyTaken commented
@KelvinChung2000 how should we proceed with this?

2024-09-25 10:19 UTC, KelvinChung2000 commented
We can keep the fix. I think it is all good now.

2024-09-25 10:19 UTC, merged